{% set name = "aiokafka" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a8fc41d18731d8879483aecb93ae7ebf5457f63daf4c8923ddc046792c2c3096

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}

  host:
    - cython >=0.29.0
    - python
    - pip
  run:
    - python
    - async_generator ==1.10  # [py<37]
    - dataclasses ==0.5  # [py<37]
    - kafka-python >=2.0.0
    - zlib

test:
  imports:
    - aiokafka

about:
  home: https://github.com/aio-libs/aiokafka
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: asyncio client for Kafka

  description: |
    AIOKafkaProducer is a high-level, asynchronous message producer.
  dev_url: https://github.com/aio-libs/aiokafka

extra:
  recipe-maintainers:
    - timkpaine
