{% set name = "aiokafka" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 8ffdc945798ba4d3d132b705d4244d0a1f493925efb57c637a2ca88ee82794e1
  - url: https://github.com/aio-libs/aiokafka/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 750e128e778690d9f33d04d7fcdebcf882230c2ced204a781245f1e6850dbf5c
    folder: gh_src

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - cython >=3.0.5
    - python
    - pip
    - setuptools >=77
    - zlib {{ zlib }}
  run:
    - python
    - async-timeout
    - packaging
    - typing-extensions >=4.10.0
  run_constrained:
    - cramjam >=2.8.0

test:
  imports:
    - aiokafka
  requires:
    - pip
    - pytest >=8.3.3
    - pytest-asyncio >=0.24.0
    - pytest-mock >=3.14.0
    - docker-py >=7.1.0
    - cramjam >=2.9.0
  source_files:
    - gh_src/tests
    - pyproject.toml
  commands:
    - pip check
    # Check that pip gets the correct version
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    # Move tests in the root folder (where pyproject.toml is)
    - move gh_src\tests tests  # [win]
    - mv gh_src/tests tests  # [not win]
    # Configure flags and docker image name (for unix only)
    # see: https://github.com/aio-libs/aiokafka/blob/master/Makefile#L3-L6
    - set FLAGS=--maxfail=3  # [win]
    - export FLAGS=--maxfail=3  # [not win]
    # Invoke tests like from the Makefile
    # see: https://github.com/aio-libs/aiokafka/blob/master/Makefile#L59
    #
    # Remove log-format for win as it was problematic, the standard format is fine.
    # Docker is not available on Windows, do not pass a docker image
    # to skip its tests (they are fine on unix).
    - pytest -s -v --log-level DEBUG %FLAGS% tests  # [win]
    # We decided to skip the docker tests for unix as well on our build system.
    # To run tests locally comment this line and un-comment the lines below it.
    - export LOG_FORMAT="%(asctime)s %(levelname)s %(message)s"  # [not win]
    - pytest -s -v --log-format="$LOG_FORMAT" --log-level DEBUG $(FLAGS) tests  # [not win]
    # - export SCALA_VERSION=2.13   # [not win]
    # - export KAFKA_VERSION=2.8.1  # [not win]
    # - export DOCKER_IMAGE=aiolibs/kafka:$(SCALA_VERSION)_$(KAFKA_VERSION)  # [not win]
    # - pytest -s -v --log-format="$LOG_FORMAT" --log-level DEBUG --docker-image=$(DOCKER_IMAGE) $(FLAGS) tests  # [not win]

about:
  home: https://github.com/aio-libs/aiokafka
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: asyncio client for Kafka
  description: |
    AIOKafkaProducer is a high-level, asynchronous message producer.
  dev_url: https://github.com/aio-libs/aiokafka
  doc_url: https://aiokafka.readthedocs.io

extra:
  recipe-maintainers:
    - timkpaine
